apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
    - "{{ .Values.virtualservice.host }}"
  gateways:
    - gateway-tls
  http:
  - match:
    #{{- range .Values.virtualservice.apis }}
    - uri:
        prefix: /spring
    #{{- end }}
    - port: 80
    rewrite:
      uri: " "
    route:
    - destination:
        port:
          number: 80
        host: {{ template "application.fullname" . }}